"""Interface publica das views do app financeiro.

Este pacote mant?m os mesmos nomes que existiam no antigo views.py,
mas organiza a implementa??o em m?dulos menores por dom?nio.
"""

from .auth import (
    ConfirmarRedefinicaoSenhaView,
    EntrarUsuarioView,
    ativar_conta,
    excluir_conta_usuario,
    marcar_notificacoes_lidas,
    pagina_inicial,
    perfil_usuario,
    registrar_usuario,
    sair_usuario,
)
from .cadastros import (
    criar_cartao,
    criar_categoria,
    criar_investimento,
    editar_cartao,
    editar_categoria,
    editar_investimento,
    excluir_cartao,
    excluir_categoria,
    excluir_investimento,
    lista_cartoes,
    lista_categorias,
    lista_investimentos,
)
from .common import (
    MercadoPagoClient,
    MercadoPagoErro,
    calcular_uso_categoria,
    calcular_parcelas_futuras,
    comparar_mes_atual_com_anterior,
    criar_lancamento_rapido,
    criar_lancamentos_recorrentes,
    detectar_gastos_pequenos_recorrentes,
    duplicar_lancamento_para_proximo_mes,
    gerar_alertas_limite_categoria,
    gerar_notificacoes_inteligentes,
    healthcheck,
    montar_acao_recomendada_hoje,
    montar_contexto_bloqueio_premium,
    montar_diagnostico_visual_ia,
    montar_fatura_cartao,
    montar_resumo_semanal,
    marcar_lancamento_como_pago,
    mensagem_erro_email_transacional,
    obter_proxima_conta_importante,
    prever_conclusao_meta,
    prever_fechamento_mes,
    sugerir_valor_para_guardar,
    sincronizar_plano_com_gateway,
    validar_assinatura_webhook_mercado_pago,
)
from .configuracoes import configuracoes
from .dashboard import dashboard
from .inteligencia import analise_ia
from .lancamentos import (
    contas_pagas,
    contas_pendentes,
    criar_recorrencia_lancamento,
    criar_lancamento,
    duplicar_lancamento_proximo_mes,
    editar_lancamento,
    excluir_lancamento,
    excluir_lancamentos_selecionados,
    lista_despesas,
    lista_lancamentos,
    lista_receitas,
    marcar_lancamento_pago,
    restaurar_lancamentos,
)
from .metas import concluir_meta, criar_meta, editar_meta, excluir_meta, lista_metas
from .pagamentos import (
    cancelar_assinatura_premium,
    checkout_premium,
    iniciar_checkout_premium,
    retorno_assinatura,
    sincronizar_assinatura_premium,
    webhook_mercado_pago,
)
from .recursos_premium import (
    cancelar_modo_contencao,
    modo_contencao,
    modo_familia,
    ranking_viloes,
    simulador_decisoes,
)
from .relatorios import relatorios

__all__ = [
    "ConfirmarRedefinicaoSenhaView",
    "EntrarUsuarioView",
    "MercadoPagoClient",
    "MercadoPagoErro",
    "analise_ia",
    "ativar_conta",
    "calcular_uso_categoria",
    "calcular_parcelas_futuras",
    "comparar_mes_atual_com_anterior",
    "cancelar_assinatura_premium",
    "cancelar_modo_contencao",
    "checkout_premium",
    "concluir_meta",
    "configuracoes",
    "contas_pagas",
    "contas_pendentes",
    "criar_cartao",
    "criar_categoria",
    "criar_investimento",
    "criar_lancamento_rapido",
    "criar_lancamento",
    "criar_lancamentos_recorrentes",
    "criar_meta",
    "criar_recorrencia_lancamento",
    "dashboard",
    "detectar_gastos_pequenos_recorrentes",
    "duplicar_lancamento_para_proximo_mes",
    "duplicar_lancamento_proximo_mes",
    "editar_cartao",
    "editar_categoria",
    "editar_investimento",
    "editar_lancamento",
    "editar_meta",
    "excluir_cartao",
    "excluir_categoria",
    "excluir_conta_usuario",
    "excluir_investimento",
    "excluir_lancamento",
    "excluir_lancamentos_selecionados",
    "excluir_meta",
    "gerar_alertas_limite_categoria",
    "gerar_notificacoes_inteligentes",
    "healthcheck",
    "iniciar_checkout_premium",
    "lista_cartoes",
    "lista_categorias",
    "lista_despesas",
    "lista_investimentos",
    "lista_lancamentos",
    "lista_metas",
    "lista_receitas",
    "marcar_notificacoes_lidas",
    "marcar_lancamento_como_pago",
    "marcar_lancamento_pago",
    "mensagem_erro_email_transacional",
    "montar_acao_recomendada_hoje",
    "montar_contexto_bloqueio_premium",
    "montar_diagnostico_visual_ia",
    "montar_fatura_cartao",
    "montar_resumo_semanal",
    "modo_contencao",
    "modo_familia",
    "obter_proxima_conta_importante",
    "prever_conclusao_meta",
    "pagina_inicial",
    "perfil_usuario",
    "prever_fechamento_mes",
    "ranking_viloes",
    "registrar_usuario",
    "relatorios",
    "restaurar_lancamentos",
    "retorno_assinatura",
    "sair_usuario",
    "simulador_decisoes",
    "sincronizar_assinatura_premium",
    "sincronizar_plano_com_gateway",
    "sugerir_valor_para_guardar",
    "validar_assinatura_webhook_mercado_pago",
    "webhook_mercado_pago",
]
