# Generated by Django 6.0.5 on 2026-05-12 20:04

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('data_limite', models.DateField()),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluida'), ('PAUSADA', 'Pausada'), ('ATRASADA', 'Atrasada')], default='EM_ANDAMENTO', max_length=15)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
                'ordering': ['status', 'data_limite', '-criada_em'],
            },
        ),
    ]
