# Generated by Django 6.0.5 on 2026-05-13 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_metafinanceira'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaocredito',
            options={'ordering': ['nome'], 'verbose_name': 'Cartão de Crédito', 'verbose_name_plural': 'Cartões de Crédito'},
        ),
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['-data_competencia', '-id'], 'verbose_name': 'Lançamento', 'verbose_name_plural': 'Lançamentos'},
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('BOLETO', 'Boleto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='metafinanceira',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='metafinanceira',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('PAUSADA', 'Pausada'), ('ATRASADA', 'Atrasada')], default='EM_ANDAMENTO', max_length=15),
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('RENDA_FIXA', 'Renda fixa'), ('ACAO', 'Ação'), ('FII', 'FII'), ('ETF', 'ETF'), ('FUNDO', 'Fundo'), ('CRIPTO', 'Cripto'), ('TESOURO', 'Tesouro'), ('OUTRO', 'Outro')], max_length=20)),
                ('instituicao', models.CharField(max_length=120)),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_atual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_aplicacao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=15)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['status', '-data_aplicacao', 'nome'],
            },
        ),
    ]
