# Generated by Django 6.0.5 on 2026-05-13 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_cartaocredito_options_alter_lancamento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda_padrao', models.CharField(choices=[('BRL', 'Real brasileiro (R$)'), ('USD', 'Dólar americano (US$)'), ('EUR', 'Euro (€)')], default='BRL', max_length=5)),
                ('formato_data', models.CharField(choices=[('BR', 'Dia/Mês/Ano'), ('ISO', 'Ano-Mês-Dia')], default='BR', max_length=10)),
                ('receber_alertas_email', models.BooleanField(default=True)),
                ('receber_alertas_vencimento', models.BooleanField(default=True)),
                ('exibir_saldo_dashboard', models.BooleanField(default=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Usuário',
                'verbose_name_plural': 'Configurações dos Usuários',
            },
        ),
    ]
