# Generated by Django 6.0.5 on 2026-05-13 13:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_configuracaousuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaocredito',
            options={'ordering': ['nome'], 'verbose_name': 'Cartao de Credito', 'verbose_name_plural': 'Cartoes de Credito'},
        ),
        migrations.AlterModelOptions(
            name='configuracaousuario',
            options={'verbose_name': 'Configuracao do Usuario', 'verbose_name_plural': 'Configuracoes dos Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['-data_competencia', '-id'], 'verbose_name': 'Lancamento', 'verbose_name_plural': 'Lancamentos'},
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='formato_data',
            field=models.CharField(choices=[('BR', 'Dia/Mes/Ano'), ('ISO', 'Ano-Mes-Dia')], default='BR', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='moeda_padrao',
            field=models.CharField(choices=[('BRL', 'Real brasileiro (R$)'), ('USD', 'Dolar americano (US$)'), ('EUR', 'Euro (EUR)')], default='BRL', max_length=5),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='tipo',
            field=models.CharField(choices=[('RENDA_FIXA', 'Renda fixa'), ('ACAO', 'Acao'), ('FII', 'FII'), ('ETF', 'ETF'), ('FUNDO', 'Fundo'), ('CRIPTO', 'Cripto'), ('TESOURO', 'Tesouro'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Cartao de Debito'), ('CREDITO', 'Cartao de Credito'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferencia'), ('BOLETO', 'Boleto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='metafinanceira',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='metafinanceira',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluida'), ('PAUSADA', 'Pausada'), ('ATRASADA', 'Atrasada')], default='EM_ANDAMENTO', max_length=15),
        ),
        migrations.CreateModel(
            name='PlanoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(choices=[('FREEMIUM', 'Freemium'), ('PREMIUM', 'Premium')], default='FREEMIUM', max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=15)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('ia_habilitada', models.BooleanField(default=False)),
                ('limite_cartoes', models.PositiveSmallIntegerField(default=1)),
                ('limite_metas', models.PositiveSmallIntegerField(default=2)),
                ('limite_investimentos', models.PositiveSmallIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano do Usuario',
                'verbose_name_plural': 'Planos dos Usuarios',
            },
        ),
    ]
