# Generated by Django 6.0.5 on 2026-05-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_cartaocredito_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planousuario',
            name='mercado_pago_checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='planousuario',
            name='mercado_pago_preapproval_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='planousuario',
            name='mercado_pago_referencia_externa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='planousuario',
            name='mercado_pago_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='planousuario',
            name='ultima_sincronizacao_gateway',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
