# Generated by Django 6.0.5 on 2026-05-13 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_planousuario_mercado_pago_checkout_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseFinanceiraIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], default='SUCESSO', max_length=10)),
                ('modelo', models.CharField(blank=True, max_length=60)),
                ('saude_financeira', models.CharField(choices=[('OTIMA', 'Otima'), ('ESTAVEL', 'Estavel'), ('ATENCAO', 'Atencao'), ('CRITICA', 'Critica')], default='ESTAVEL', max_length=12)),
                ('resumo_executivo', models.TextField(blank=True)),
                ('contexto_enviado', models.JSONField(blank=True, default=dict)),
                ('metricas_resumo', models.JSONField(blank=True, default=dict)),
                ('sinais_positivos', models.JSONField(blank=True, default=list)),
                ('alertas_prioritarios', models.JSONField(blank=True, default=list)),
                ('oportunidades', models.JSONField(blank=True, default=list)),
                ('plano_acao', models.JSONField(blank=True, default=list)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('resposta_bruta', models.JSONField(blank=True, default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analise Financeira IA',
                'verbose_name_plural': 'Analises Financeiras IA',
                'ordering': ['-criada_em'],
            },
        ),
    ]
