# Generated by Django 6.0.5 on 2026-05-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_analisefinanceiraia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='foto_perfil',
            field=models.FileField(blank=True, upload_to='perfis/'),
        ),
    ]
