# Generated by Django 6.0.5 on 2026-05-14 12:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_configuracaousuario_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoContencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Modo anti-descontrole', max_length=120)),
                ('duracao_dias', models.PositiveSmallIntegerField(choices=[(7, '7 dias'), (15, '15 dias'), (30, '30 dias')])),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('data_fim', models.DateField()),
                ('orcamento_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_contencao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Contencao',
                'verbose_name_plural': 'Planos de Contencao',
                'ordering': ['-data_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LimiteCategoriaContencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_contencao', to='financeiro.categoria')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='financeiro.planocontencao')),
            ],
            options={
                'verbose_name': 'Limite por Categoria',
                'verbose_name_plural': 'Limites por Categoria',
                'ordering': ['categoria__nome'],
                'unique_together': {('plano', 'categoria')},
            },
        ),
    ]
