# Generated by Django 6.0.5 on 2026-05-14 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_planocontencao_limitecategoriacontencao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='escopo',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPARTILHADO', 'Conjunto')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='OrcamentoCompartilhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('CASAL', 'Casal'), ('FAMILIA', 'Família')], default='CASAL', max_length=15)),
                ('codigo_convite', models.CharField(blank=True, max_length=12, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento Compartilhado',
                'verbose_name_plural': 'Orçamentos Compartilhados',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='orcamento_compartilhado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.orcamentocompartilhado'),
        ),
        migrations.CreateModel(
            name='MembroOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ADMIN', 'Administrador'), ('MEMBRO', 'Membro')], default='MEMBRO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_compartilhados', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='financeiro.orcamentocompartilhado')),
            ],
            options={
                'verbose_name': 'Membro do Orçamento',
                'verbose_name_plural': 'Membros dos Orçamentos',
                'ordering': ['usuario__first_name', 'usuario__username'],
                'unique_together': {('orcamento', 'usuario')},
            },
        ),
    ]
