# Generated by Django 6.0.5 on 2026-05-14 17:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_lancamento_escopo_orcamentocompartilhado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CHECKOUT_CRIADO', 'Checkout criado'), ('WEBHOOK_RECEBIDO', 'Webhook recebido'), ('SINCRONIZACAO', 'Sincronizacao'), ('PREMIUM_ATIVADO', 'Premium ativado'), ('PREMIUM_CANCELADO', 'Premium cancelado'), ('ACESSO_BLOQUEADO', 'Acesso bloqueado'), ('ERRO', 'Erro')], max_length=30)),
                ('origem', models.CharField(choices=[('SISTEMA', 'Sistema'), ('MERCADO_PAGO', 'Mercado Pago'), ('USUARIO', 'Usuario')], default='SISTEMA', max_length=20)),
                ('mercado_pago_preapproval_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('mercado_pago_evento_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('mercado_pago_tipo', models.CharField(blank=True, max_length=80)),
                ('mercado_pago_acao', models.CharField(blank=True, max_length=80)),
                ('status_gateway', models.CharField(blank=True, max_length=40)),
                ('referencia_externa', models.CharField(blank=True, max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('moeda', models.CharField(default='BRL', max_length=5)),
                ('mensagem', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_assinatura', to='financeiro.planousuario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_assinatura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Assinatura',
                'verbose_name_plural': 'Eventos de Assinatura',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['tipo', 'criado_em'], name='financeiro__tipo_da2c7a_idx'), models.Index(fields=['usuario', 'criado_em'], name='financeiro__usuario_077254_idx'), models.Index(fields=['status_gateway', 'criado_em'], name='financeiro__status__0cc93a_idx')],
            },
        ),
    ]
