# Generated by Django 6.0.5 on 2026-05-15 11:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0011_eventoassinatura"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracaousuario",
            options={
                "verbose_name": "Configuração do Usuário",
                "verbose_name_plural": "Configurações dos Usuários",
            },
        ),
        migrations.AlterModelOptions(
            name="lancamento",
            options={
                "ordering": ["-data_competencia", "-id"],
                "verbose_name": "Lançamento",
                "verbose_name_plural": "Lançamentos",
            },
        ),
        migrations.AddField(
            model_name="metafinanceira",
            name="estrategia",
            field=models.CharField(
                choices=[
                    ("AGRESSIVA", "Meta Agressiva"),
                    ("SUAVE", "Meta Suave"),
                    ("CONSERVADORA", "Meta Conservadora"),
                ],
                default="SUAVE",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="metafinanceira",
            name="valor_semanal_planejado",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="eventoassinatura",
            name="origem",
            field=models.CharField(
                choices=[
                    ("SISTEMA", "Sistema"),
                    ("MERCADO_PAGO", "Mercado Pago"),
                    ("USUARIO", "Usuário"),
                ],
                default="SISTEMA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lancamento",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("DEBITO", "Cartão de Débito"),
                    ("CREDITO", "Cartão de Crédito"),
                    ("PIX", "PIX"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("BOLETO", "Boleto"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="metafinanceira",
            name="prioridade",
            field=models.CharField(
                choices=[("BAIXA", "Baixa"), ("MEDIA", "Média"), ("ALTA", "Alta")],
                default="MEDIA",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="metafinanceira",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_ANDAMENTO", "Em andamento"),
                    ("CONCLUIDA", "Concluída"),
                    ("PAUSADA", "Pausada"),
                    ("ATRASADA", "Atrasada"),
                ],
                default="EM_ANDAMENTO",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("mensagem", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INFO", "Informação"),
                            ("SUCESSO", "Sucesso"),
                            ("ALERTA", "Alerta"),
                            ("ERRO", "Erro"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=255)),
                ("lida", models.BooleanField(default=False)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-criada_em", "-id"],
            },
        ),
    ]
