# Generated by Django 6.0.5 on 2026-05-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0012_alter_configuracaousuario_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaousuario",
            name="foto_perfil_binario",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuracaousuario",
            name="foto_perfil_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="configuracaousuario",
            name="foto_perfil_nome",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
