# Generated by Django 6.0.5 on 2026-05-18 13:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0013_configuracaousuario_foto_perfil_binario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="limite_mensal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
